### ISSUE TITLE
Add some usage examples to readme

### ISSUE THREAD

**Issue by frederickfogerty** [imgix/react-imgix#11]
It would be helpful to have some different examples, for instance, no cropping, entropy cropping, face cropping, background mode, image mode, etc.

**Comment by frederickfogerty** [comment]
@paulstraw any update on this?

**Comment by paulstraw** [comment]
Hey @frederickfogerty, I haven't had an opportunity to build these examples out yet. I'm really booked up this week, but can try to get it taken care of next week?
