### ISSUE TITLE
Support for sizes, and width descriptors

### ISSUE THREAD

**Issue by oyeanuj** [imgix/react-imgix#115]
Hey @frederickfogerty, thanks for putting out this library. Somewhat connected to #71, but while trying to use to do responsive images, I noticed that the library doesn't currently support `sizes` prop for `<img>`, or width descriptors (density descriptors seem to be supported via `dpr`) within `srcSet`.

Not sure if I missed something, or if there was a reason for that? If not, would this be something on the radar to add?

Thanks!

**Comment by oyeanuj** [comment]
@frederickfogerty Just following up here, if you had any thoughts on this? Thank you!

**Comment by frederickfogerty** [comment]
Hey there @oyeanuj! 

I don't know a lot about `sizes`, and `srcSet` - could you please outline what you think the advantages and use cases (examples) of implementing each feature you've described would be? From there we can assess whether it should be added to the API. 

Thanks :)

**Comment by frederickfogerty** [comment]
This will be fixed in the next major version, v8.
