### ISSUE TITLE
Lazysizes with react-imgix

### ISSUE THREAD

**Issue by sergejr** [imgix/react-imgix#117]
Hey, is there an opportunity to use react-imgix with lazysizes?
If yes, how?

Thanks.

**Comment by frederickfogerty** [comment]
Hey there @sergejr 😄 

I have no experience with `lazysizes`, so I cannot help in getting it working with this library. Is this something that is very important to you?

**Comment by frederickfogerty** [comment]
I've never heard of the "qlip method", and I can't find anything online. I'm curious, what is it?

**Comment by sergejr** [comment]
Sorry, It was LQIP.. My fault.
It works with a data-src attribute.
https://blog.imgix.com/2016/06/01/lqip-your-images.html
With the React Imgix Component and the usage of the Picture Tag it's not possible to pass a data-attribute with another Image Source. Would be great to archive a Preload "Animation". Or do you have another idea?

Currently I've added customParameter and after this I've written a function to remove the modes from the source URL to archive the preload.

**Comment by frederickfogerty** [comment]
Oh cool! We talked about this in #14, but I never got round to implementing it as I didn't need it for my use back then...

Can you share the specifics (i.e. code) of what you're doing now? And would you be interested in contributing this to the library yourself?

**Comment by sergejr** [comment]
Here's an example:
https://gist.github.com/sergejr/db8d481e576ba60ea89fdd185fd4207b

**Comment by frederickfogerty** [comment]
As that example works with the DOM directly, I'm not comfortable working that into the main component, but a version of this could be worked in to use React state, etc to perform the same effect. Is this something you'd be interested in working on?

**Comment by sergejr** [comment]
That's true. I was looking for a Solution without working inside the Package Core to allow further updates.
Yes, I would be interested in working on that Feature.

**Comment by frederickfogerty** [comment]
Awesome @sergejr 🚀

The first step would be to work out and agree on an API for the feature (aiming to keep it as simple as possible), and then implementing the feature inside the component. 

I'll be available here if you need any help.
