### ISSUE TITLE
Background URLs containing parenthesis do not display

### ISSUE THREAD

**Issue by nickhavenly** [imgix/react-imgix#118]
I ran into an edge case where certain URLs in our buckets have a left parenthesis `(` as part of the URL string. This breaks the `background-image:` style resulting in a blank image.

I did a little testing locally and found line 150 to be the culprit: 
https://github.com/imgix/react-imgix/blob/facbbdd3c48f205acd7ae7dc2947020a2fb4715d/src/index.js#L150

A quick test adding single quotes around the url seems to solve this problem for me:
`url('${_src}')`

**Comment by frederickfogerty** [comment]
Hey @nickhavenly, sorry about the delay -- is this something you would be interested in submitting a PR for?

**Comment by nickhavenly** [comment]
Sure thing, I'll have that up in a few.
