### ISSUE TITLE
Setting width (height) props, sets the width (height) on the <img> tag

### ISSUE THREAD

**Issue by panayi** [imgix/react-imgix#127]
This:

```javascript
<Imgix 
  src="images/example.png"
  width={87}
  height={87}
  fit="fill"
/>
```

outputs an `img` with width and height props:

```html
<img 
  width="87" 
  height="87" 
  srcset="..." 
  src="https://example.imgix.net/images/example.png?auto=format&amp;dpr=1&amp;crop=faces&amp;fit=fill&amp;w=87&amp;h=87"
/>
```

Which renders this:

![image](https://user-images.githubusercontent.com/707005/34842155-4f24b1aa-f713-11e7-8351-ef17fcc37bc8.png)

instead of this:

![image](https://user-images.githubusercontent.com/707005/34842200-76c6dc92-f713-11e7-9545-7acd7128ef0d.png)

**Comment by frederickfogerty** [comment]
Hey there,

Using `defaultWidth` and `defaultHeight` seems to fix this issue for me.

```js
  <Imgix
		src="https://assets.imgix.net/unsplash/bridge.jpg"
		defaultWidth={87}
		defaultHeight={87}
		fit="fill"
	/>
```

Renders

<img srcset="https://assets.imgix.net/unsplash/bridge.jpg?auto=format&amp;dpr=2&amp;crop=faces&amp;fit=fill&amp;w=87&amp;h=87 2x, https://assets.imgix.net/unsplash/bridge.jpg?auto=format&amp;dpr=3&amp;crop=faces&amp;fit=fill&amp;w=87&amp;h=87 3x" src="https://assets.imgix.net/unsplash/bridge.jpg?auto=format&amp;dpr=1&amp;crop=faces&amp;fit=fill&amp;w=87&amp;h=87">

**Comment by frederickfogerty** [comment]
I'm going to close this issue due to inactivity. If this still an issue please comment on this issue or open a new issue.
