### ISSUE TITLE
Support Variable Qualities for SrcSet

### ISSUE THREAD

**Issue by AdamPflug** [imgix/react-imgix#129]
**type:** feature request

When working with SrcSets I find it's pretty important to specify lower encoding qualities for the high-dpi images, otherwise you end up with your largest file sizes being served to mobile devices (which are most sensitive to file size). This is because phones/tablets tend to both display images full width instead of in columns, and are more likely to have high DPI screens. High resolutions with high compression ratios still look significantly better at similar file sizes to lower resolution uncompressed images on these displays, so it's still worth using srcsets rather than just leaving them off.

In fact, this mirrors the Imgix's own recommendation: https://docs.imgix.com/tutorials/responsive-images-srcset-imgix (See "Use Variable Quality")

The trick is, I can't find a way to specify parameters per-dpi with this library. My first thought about what the API would look like would be something like this:

```jsx
<Imgix src={url} faces={false} fit="max" generateSrcSet={[{q: 95}, {q: 75}, {q: 50}]} /> 
```

where each element in the array is basically a `customParams` object, but specifically targeted at that srcset entry (so the first one is 1x, the second one is 2x, the third is 3x). This is super flexible (supports more than just changing the quality), and would potentially even unlock custom dprs like this:

```jsx
<Imgix src={url} generateSrcSet={[{q: 95, dpr: 1}, {q: 75, dpr: 1.5}, {q: 50, dpr: 2}]} /> 
```

Thoughts? Am I missing something?

Thanks!

- Adam

**Comment by frederickfogerty** [comment]
Hey Adam!

Thanks for the great suggestion! Your API does seem like an intuitive one, and would be a welcome addition to this library. 

Unfortunately I can't commit time to this project at the moment, and as such I can't guarantee I'd be able to develop this. If you have some time and would be happy to contribute this to the repository, I'd happily take a PR for this!

Cheers, Fred

**Comment by frederickfogerty** [comment]
Hey there @AdamPflug - I'm now working for Imgix now, so I have more time to dedicate to features like this. After speaking with the team, we think is a great idea and we'll look to support this (or something with the same effect) soon - I can't give an exact timeline unfortunately.

**Comment by AdamPflug** [comment]
Sounds great, thanks!

**Comment by zachafranz** [comment]
Hey @frederickfogerty was just wondering about the status/progress of this feature?

**Comment by jayeb** [comment]
Hey @zachafranz, Jason from imgix here. There's no progress on this feature at the moment--we're currently focusing our SDK efforts around cleaning up & unifying our existing code across all of our libraries before we start adding new features like this.

That being said, we'd happily make time to review PRs from the community, so if you want to take a swing at this one we'd love to help from there!
