### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by samuelcole** [imgix/react-imgix#13]
Hi, do you mind publishing a new version containing https://github.com/imgix/react-imgix/commit/4034663c7af52b4e400a44fd1942d2910e51259b.

I'm seeing a lot of errors from `Object.assign`, and I believe they are from this component.

**Comment by paulstraw** [comment]
Hey @samuelcole, good catch. I've published version 2.1.2 to NPM.

**Comment by frederickfogerty** [comment]
:rocket:
