### ISSUE TITLE
LQIP Images

### ISSUE THREAD

**Issue by harrisrobin** [imgix/react-imgix#130]
**type:** feature request

**react-imgix version:** `v1.0`

It would be nice to have medium.com style progressive loading, like [this](https://github.com/GraphCMS/graphcms-image) and have a component to load imgix images. The need for the former made me not want to use this component, both would be great. 

I would imagine a prop to enable it, and then by providing an imgix url it would do what graphcms-image can do with some sensible defaults.

**Comment by frederickfogerty** [comment]
Hey man,

Funnily enough this was one of the first ideas I had with this library, but never got around to making it. It can somewhat be faked by using a `pjpg`, but there's not first class support for it right now.

As you may have seen in other issues, I can't commit time to this project right now, but I'd happy help you develop this and accept a PR for it if you wanted :)

**Comment by harrisrobin** [comment]
@frederickfogerty Sure! I'd be interested in submitting a PR for this. 

Let me look into it next week and see if I can come up with something and I'll mention you in the PR to get your take on it.

Cheers

**Comment by frederickfogerty** [comment]
Hey @harrisrobin we're looking to implement first class support for lazysizes, which should provide support for LQIP images 👍 I'm gonna close this for now.
