### ISSUE TITLE
Picture Support for Responsive images not working

### ISSUE THREAD

**Issue by woss** [imgix/react-imgix#132]
**type:** question

**react-imgix version:** `7.1.1`

**Code**

```js
<div className={classes.image}>
  <Imgix
    src={src}
    onMounted={ar => {
      console.log(ar)
    }}
    width={1400}
    fit={'clip'}
    auto={['format', 'compress']}
    type="picture"
  >
    <Imgix
      src={src}
      width={400}
      type="source"
      imgProps={{media: '(min-width: 768px)'}}
    />
    <Imgix
      src={src}
      width={200}
      type="source"
      imgProps={{media: '(min-width: 320px)'}}
    />
  </Imgix>
</div>
```

**Actual behavior:**
For some reason it resizes it to really finny size.

[![Screen_Shot_2018-06-08_at_15.25.22.png](https://s22.postimg.cc/mdwthep0x/Screen_Shot_2018-06-08_at_15.25.22.png)](https://postimg.cc/image/qaa5dea0d/)

React Version: 16.3.2

**Comment by frederickfogerty** [comment]
Sorry for the radio silence, this should be fixed in the latest version of Imgix. 

The problem here was that the fallback image was rendering at a width of `1400px`, which caused all the other sources to render at that resolution too.
