### ISSUE TITLE
Preload blurred/low-res image

### ISSUE THREAD

**Issue by frederickfogerty** [imgix/react-imgix#14]
Something like this: https://jmperezperez.com/medium-image-progressive-loading-placeholder/

We have this working internally by hacking around react-imgix. Will probably look to open-source this soon.

**Comment by paulstraw** [comment]
You might be able to avoid having to deal with this by using `fm=pjpg` instead. This will return a progressive JPEG file that will initially render in a similar fashion, and won't require an additional request.

**Comment by frederickfogerty** [comment]
@paulstraw really? having a look at that now!

**Comment by frederickfogerty** [comment]
Hey @paulstraw yeah that's a quick fix, but still not really an ideal solution. This enhancement still stands

**Comment by anaibol** [comment]
Something like this? https://jmperezperez.com/medium-image-progressive-loading-placeholder/

**Comment by andykent** [comment]
We do this on https://www.kindness.org and it's pretty awesome.

I don't have time to make a PR right now but below is the component we use, might be of help to someone who wants to pick this up.

https://gist.github.com/andykent/2574cf9e50a014a7a64ea0ee4b88ab3b

**Comment by frederickfogerty** [comment]
Looks awesome @andykent, thanks for sharing.

At this stage I'm working on another project which doesn't use imgix, so it doesn't make sense for me to implement it, but maybe in the future I'll start working with imgix again.

**Comment by oyeanuj** [comment]
@frederickfogerty Curious where you ended up with this? 

For anyone around: It seems like the options are to either load a progressive JPEG  or load a really small image and scale it for blur or use @andykent's solution above to load a custom blurred image until the main one is loaded?

**Comment by frederickfogerty** [comment]
@oyeanuj I didn't make any progress with this.

Thanks for the note. Would you be interested in implementing for this library? If not, I'm going to close this issue, as I won't be implementing this.

**Comment by oyeanuj** [comment]
@frederickfogerty I can definitely share my solution if I can find some consensus or recommended way of implementing this. Any thoughts there?

**Comment by frederickfogerty** [comment]
@oyeanuj I'm sure it would be valuable to share your solution in a gist at least, and then if this gathers more interest we could implement it internally.
