### ISSUE TITLE
Add mention-bot

### ISSUE THREAD

**Issue by frederickfogerty** [imgix/react-imgix#18]
You know, for that sweet PR workflow. Since I don't have ownership anymore ( :sob: ) I can't do this.

### How To Use?

- Go to
 - your project on GitHub > Settings > Webhooks & services > Add Webhook or
 - your organization on GitHub > Settings > Webhooks > Add Webhook
- Payload URL: `https://mention-bot.herokuapp.com/`
- Let me select individual events > Check `Pull Request`
- Add Webhook

And you are done. Next time a pull request is opened, you should see the bot add a comment ;)

https://github.com/facebook/mention-bot

**Comment by paulstraw** [comment]
Oh, that was definitely an oversight. I just re-added you as admin.

**Comment by paulstraw** [comment]
Just added this though, should be set.

**Comment by frederickfogerty** [comment]
Hmm... Maybe someone else needs to submit a PR. We'll see how it goes.
