### ISSUE TITLE
Thoughts on option to strip protocol from urls.

### ISSUE THREAD

**Issue by tryggvigy** [imgix/react-imgix#21]
Many services return image urls with `http://` as the protocol. If requested over `https://` they will result in errors.

A boolean prop that would strip the protocol from the `src` attribute would be useful for many developers.
```jsx
<Imgix
  src={imageUrl}
  stripProtocol
/>
```

Would you be interested in a PR implementing this?

**Comment by frederickfogerty** [comment]
@tryggvigy yup! I would accept a PR for that.

I've also thought about adding something like `domain` and then `route` or `image` so the user wouldn't have to worry about joining urls etc. What do you think?

**Comment by tryggvigy** [comment]
@frederickfogerty Thanks for the swift reply!
I think string concatenation is less of an issue for devs especially with template strings.
On the other hand removing specific parts of a string (e.g. protocol) is more off a hassle.

At least thats my opinion! Keeping the API surface small is awesome. :smile: 

With your blessing I will start work on a PR implementing `stripProtocol` 
attribute as soon as possible.

**Comment by frederickfogerty** [comment]
Closing as discussion developed in #22
