### ISSUE TITLE
Remove "fallback src" in srcset generation

### ISSUE THREAD

**Issue by jayeb** [imgix/react-imgix#227]
**Describe the bug**
We're currently adding a "sizeless" source URL to the end of our `srcset` attributes as a "fallback source", which is incorrect. The "fallback source" for an image element using the `srcset` attribute should be provided in the `src` attribute, not at the end of the `srcset` list.

See the lines in question here: https://github.com/imgix/react-imgix/blob/master/src/react-imgix.js#L124-L125

**To Reproduce**
N/A

**Expected behaviour**
Every item in the `srcset` list should include a size descriptor, which in our case is always a width value or a resolution multiplier.

**Information:**
- react-imgix version: >= 8.0.0

**Additional context**
This issue is also present in imgix-rails, and is being fixed here: https://github.com/imgix/imgix-rails/pull/69

**Comment by frederickfogerty** [comment]
I've managed to sneak this into #224.

For Github: Closed by #224

**Comment by frederickfogerty** [comment]
Fixed by #224

**Comment by frederickfogerty** [comment]
Released in `8.4.0` 🎉
