### ISSUE TITLE
agressiveLoad typo

### ISSUE THREAD

**Issue by KristerV** [imgix/react-imgix#23]
There seems to be a mismatch in code and docs:

*in the docs*
`aggressiveLoad={bool}`

*in the code*
`aggresiveLoad: false`
https://github.com/imgix/react-imgix/blob/master/src/index.js#L45

**Comment by paulstraw** [comment]
Hey @frederickfogerty, since this will technically be a breaking change, do you have any issue with me merging it in and then releasing a `3.0.0`?

**Comment by frederickfogerty** [comment]
@paulstraw I saw this a few days ago and have been thinking about it. We could probably just add `aggressiveLoad` as the same functionality and just deprecate `aggresiveLoad`. Is there really a point in releasing a breaking change just for one spelling mistake? This was the internal debate I was having with myself

**Comment by paulstraw** [comment]
Sorry for the delayed response, I was at RailsConf this week. I think in this case, I'm leaning a bit towards just ripping the band-aid off and doing the breaking change. The library is still relatively young, and I think I'd prefer to just have this done with.

That being said, I don't have super strong feelings about it either way, so I'll defer to you for the final decision. Just let me know, and I'll be happy to do either change if you want. 😄

**Comment by frederickfogerty** [comment]
@paulstraw let's just make it breaking then :) I'll let you make the change if you don't mind
