### ISSUE TITLE
Fluid on one dimension

### ISSUE THREAD

**Issue by minfawang** [imgix/react-imgix#25]
I'm trying to make the image fluid on only one dimension, but this library seems to not allow me to do it.

One way to resolve it I think is to support float height/width (https://docs.imgix.com/apis/url/size/h). Right now if I pass the props of `height = 1.0` to the component, it outputs an image literally with height of 1px, which is behaving differently from the imgix documentation.

**Comment by minfawang** [comment]
Although I just found the [image-height](https://github.com/imgix/react-imgix/blob/master/src/support.js#L85) option in the `customParams`, it doesn't work, because the [auto-calculated height](https://github.com/imgix/react-imgix/blob/master/src/index.js#L104-L111) takes precedence and will always overwrite it.

**Comment by frederickfogerty** [comment]
Hi @minfawang would you be able to provide some sample usage that you are trying to use, and the actual and expected urls? This will help me better understand the problem

**Comment by minfawang** [comment]
Yes. So I'm trying to let the image fluid only on width. The height will be calculated based on the current width (keeping the aspect ratio). The desired url will have params of `w=node.scrollWidth` and `h=1.0`. Right now I can get that params by passing in the following props:
~~~javascript
<Imgix fluid height={1.0} />
~~~

However, it doesn't really work in this package, because the height is added to attribute of the `img` html tag directly and force the `img` to have the height of 1px.

Does this explanation make sense? I'm happy to provide more info if needed.

**Comment by minfawang** [comment]
I think to make this question more general is: Right now the `height` and `width` props is only able to interpret the input as the actual pixel value. Do you think it make sense to support float value, so the behavior is more aligned with [image API documentation](https://docs.imgix.com/apis/url/size/h) of imgix?

**Comment by frederickfogerty** [comment]
Sorry, maybe I should have been clearer, the easiest for me is:
**Usage:** `<Imgix fluid height={1.0} />` 
**Expected:** `https://foobar.imgix.net/img.jpg?h=1&fm=auto`
**Actual:**  `https://foobar.imgix.net/img.jpg?h=9000&fm=screwed_up`

This allows me to write test cases for your requests so I can ensure I have fixed the problem.

Also for your request to support floats, I see that being valid, so please include an example like above with floats as props and we can discuss.

**Comment by frederickfogerty** [comment]
I just reread your comments and it seems like the problem with the rendering of the element, not necessarily the request to Imgix, is this correct?

**Comment by minfawang** [comment]
Yeah. The problem is rendering the element, but not the request. 

Because of [this line](https://github.com/imgix/react-imgix/blob/master/src/index.js#L119), the props of `height` is passed down to the element. The image below could explain:

![image](https://cloud.githubusercontent.com/assets/8814693/15231232/b2a45dde-184e-11e6-86b7-52e9ce00b294.png)

Look the `img` tag has attribute of `height=1`, which restricts the height of the image to be 1px.

**Comment by frederickfogerty** [comment]
Oops.

**Comment by minfawang** [comment]
So... is there a tentative schedule to fix it? 😸

**Comment by frederickfogerty** [comment]
@minfawang hey man, sorry, been really busy. I probably won't have time to look at this soon - you can submit a PR if you want and I'll review it, otherwise I will fix it in a few weeks :)

**Comment by minfawang** [comment]
Totally understand. Just sent a PR. Probably the simplest way to fix it..

**Comment by minfawang** [comment]
Wonder if we can publish a new release to npm with this update?

**Comment by frederickfogerty** [comment]
@minfawang done :)
