### ISSUE TITLE
Unknown Prop Warning in React 15.2.1

### ISSUE THREAD

**Issue by theolampert** [imgix/react-imgix#33]
I get this [react warning](https://facebook.github.io/react/warnings/unknown-prop.html) when updating to the latest react version `15.2.1`. As far as I can tell being more explicit about what props are passed to the `img` tag fixes the warning for me. You can see the approach I took on my [fork](https://github.com/theolampert/react-imgix/commit/fa925c43c9671d19d920befaf63ca4b8289a287d). Happy to submit a PR but wanted to know if this is the best approach?.

**Comment by paulstraw** [comment]
Hmm… that `...other` is important in this case to allow things like setting the `alt` attribute. @frederickfogerty, any thoughts on best practices here?

**Comment by theolampert** [comment]
@paulstraw that makes sense, maybe we can pass whats used by the `img` node rather than all the remaining props?. Let me know what you think.

**Comment by frederickfogerty** [comment]
So, the idea with `...other` is that it would allow the consumer of the component to pass whatever props they wanted to the `img` or `div`, if they wanted to. Here are a few options to fix this:

1. Remove the above (undocumented) functionality, and go with an implementation like  @theolampert's.
2. Introduce a function through which we pass the props we are going to pass to the component. This function just picks off the object the valid/allowed img props, and the rest are discarded.
3. Do (1), but also add a prop to the component, e.g. `overrides`, which allows the user to override props.

I think either 2 or 3 are the best options. Thoughts? 

cc @paulstraw

**Comment by theolampert** [comment]
After reading through [this thread](https://github.com/Hacker0x01/react-datepicker/issues/517#issuecomment-230119718) and suggested fixes here are our thoughts. The main thing here is to make sure the lib itself isn't passing anything we *know* shouldn't be on the dom node, if the user passes unsupported props that is their issue.

1. This doesn't work really as it breaks the ability to pass any attributes to the DOM node. 

2. This would mean maintaining a custom whitelist of attributes for both the img node and the div which isn't ideal.

3. This could work and is also suggested in that thread, however maybe we could think about a different name? `imgProps` for instance?.

so
```javascript
let childProps = {
  ...other,
  width: other.width <= 1 ? null : other.width,
  height: other.height <= 1 ? null : other.height
}
```
becomes something like...
```javascript
let childProps = {
  ...this.props.imgProps,
  width: other.width <= 1 ? null : other.width,
  height: other.height <= 1 ? null : other.height
}
```

A fourth option (also suggested above) is to make a shallow copy of the props object and delete the unused props from it before applying this to the DOM node. What do you think?

**Comment by frederickfogerty** [comment]
I do like the fourth option...

But I think we should probably do the fourth option. In the future, if we start handling different img props and start messing with behaviours, we could start running into bad breaking changes, but if we explicitly move the prop from `imgProps` to a base prop, then the user of the component understands that at least we are doing something with it. What do you think?

**Comment by theolampert** [comment]
@frederickfogerty sounds good, I'm for option three as well - it seems to make the most sense here. I'm happy to submit a pr for this in the next few days unless you'd like to?
