### ISSUE TITLE
Using `<Background />` tanks my CPU

### ISSUE THREAD

**Issue by drydenwilliams** [imgix/react-imgix#387]
**Describe the bug**
I have a media gallery which loads set background images using the `<Background />` component and as soon as I started using it, my CPU load spike massively. 

![Screenshot 2019-06-14 at 13 05 53](https://user-images.githubusercontent.com/4403089/59508308-606cc580-8ea5-11e9-83ab-926bdcede29b.png)

Different between not using the `<Background />` component in the first half of the graph. And using it in the second half. 

<img width="557" alt="Screenshot 2019-06-14 at 13 11 03" src="https://user-images.githubusercontent.com/4403089/59508474-fdc7f980-8ea5-11e9-9c3f-2849fbe339d7.png">

**To Reproduce**
Add a list of images using the `<Background />` component and see the spike in CPU.

```
<Background
  src={imageSrc}
  imgixParams={{
    crop: 'entropy',
    h: 200,
    w: 200
  }}
  className="blog-title"
>
 Title
</Background>
```
**Information:**

- react-imgix version: [e.g. v8.6.1]
- browser version: https://whatsmybrowser.org/b/RAF3DEX(https://www.whatsmybrowser.org/

**Comment by ericdeansanchez** [comment]
Hey @drydenwilliams, I'm currently working on solving this issue. The `<Background/>` component is constantly re-rendering. The fix I'm working on aims to ensure minimal re-renders.
