### ISSUE TITLE
CodeSandbox links from the readme are on 7.2.0

### ISSUE THREAD

**Issue by VitamintK** [imgix/react-imgix#389]
**Before you submit:**

- [x] Please search through the existing issues (both open AND closed) to see if your issue has been discussed before. Github issue search can be used for this: https://github.com/imgix/react-imgix/issues?utf8=%E2%9C%93&q=is%3Aissue
- [x] Please ensure the problem has been isolated and reduced. This link explains more: http://css-tricks.com/6263-reduced-test-cases/

**Describe the bug**
Readme has links to codesandbox.io links that look like they're using react-imgix 7.2.0., so it seems like at least the `sizes` prop has no effect.  Also, the code in CodeSandbox doesn't match that of the documentation that links to it - the doc for "Basic use case" has a sizes prop, but the CodeSandbox does not.

By pressing the little "refresh" symbol next to "react -imgix 7.2.0" on the left sidebar in the codesandbox.io pages, the rendered html becomes different.

**To Reproduce**
Steps to reproduce the behaviour:

1.  Go to https://github.com/imgix/react-imgix
2. In Examples > Basic use case, click on "Edit on CodeSandbox"
3. observe that the CodeSandbox code doesn't have a "sizes" prop, and if you manually add one, it does not change the rendered HTML, and the version of react-imgix in the dependencies is 7.2.0

**Expected behaviour**

Instead, the version of react-imgix should be 8.6.0., and the code in CodeSandbox should have `sizes` prop like in the readme that links to it.

**Screenshots**

**Information:**

- react-imgix version: [e.g. v1.0]
- browser version: [include link from [https://www.whatsmybrowser.org/](https://www.whatsmybrowser.org/) or details about the OS used and browser version]

**Additional context**

**Comment by sherwinski** [comment]
hey @VitamintK thanks for bring this to our attention.
@frederickfogerty, think you'd be able to help with this? Looks like the two codepens linked in the docs are both under your account. Thanks!
https://codesandbox.io/s/4z1rzq04q7?view=preview
https://codesandbox.io/s/xp0348lv0z?view=preview

**Comment by frederickfogerty** [comment]
Hey @sherwinski 👋 I'm happy to do this, but I was thinking it might be better to fork these codesandboxes and bring them under an @imgix org account for future updates?

**Comment by sherwinski** [comment]
@frederickfogerty that's a great point 😀
