### ISSUE TITLE
Feature request: Memoize buildSrc

### ISSUE THREAD

**Issue by baldurh** [imgix/react-imgix#405]
Even after the latest optimizations in #395 `buildSrc` is still my server’s second hottest frame (see below)

In that PR @frederickfogerty suggested adding memoization to `buildSrcSetPair` https://github.com/imgix/react-imgix/pull/395#discussion_r298668266

I had thought about it but decided to not do anything about it in that PR.

I think the best argument for memoization is server-side rendering as it is processing the same urls over and over while it’s running. So I wanted to discuss what approach you’d think would be best before creating a PR.

Two options come to mind:
**Implement memoization internally**
We’d just memoize everything. This of course would both make the component and memory footprint larger.
We could have it configurable, either global opt-in or per usage (component prop). This would still make the component larger.

**Plug-in memoization**
We could add a way for user’s to plug-in their own memoization mechanism. This way it would be purely opt-in. Almost no additional code would be added to the library. This would also allow user’s to easily turn on memoization server-side only if they want.

I’d love to hear your thoughts on this.

My server’s flamegraph for 10 requests

![image](https://user-images.githubusercontent.com/1823617/60877796-07871780-a22e-11e9-83c8-fab60962eaed.png)

**Comment by frederickfogerty** [comment]
Hey @baldurh! Thanks for the further investigation! 

I know I suggested memoization, and I still don't think it's a bad idea, but I had another idea that I think should be investigated first. 

We should be making sure that the hot path (buildSrc and child functions) are all able to be optimized by Node's JIT compiler. If the functions are not being optimized, we could be seeing a slowdown of 3-5x (based on a quick google search). This will improve both server-side rendering (Node) and client side rendering (Chrome implements a lot, if not all, of the same optimizations).

----

Regarding the memoization:

Firstly, I just wanted to clarify this statement: "processing the same urls over and over while it’s running". Do you mean this as in across separate requests from different users/pages? I agree with this, but if it was more "the same urls *in the same request*", then I'd be interested to see how true this was in the real world.

I think the first option to implement memoization internally makes more sense. Also, I think that per-component makes the most sense, which is what we've reverted to in the past, as you can easily make a "global" setting using the per-component prop:

```jsx
// index.js
const ImgixWithMemoization = (props) => <Imgix memoize {...props} />;

// component
const Header = (props) => (
<div>
  ...
  <ImgixWithMemoization ... />
</div>
);
```

**Comment by baldurh** [comment]
> If you're able to post a more detailed photo of just `buildSrc` and its children, that would be useful to see what the hot path(s) is.

Here’s the [current flamegraph](https://upload.clinicjs.org/public/74f58d67e4cf5249354ebb47e49887fb9a054768b274de701798a953c1aeeb93/16148.clinic-flame.html#selectedNode=163&zoomedNode=&exclude=83c0&merged=true) for when running buildSrc in a loop

Here’s [one with the stuff I’m experimenting with](https://upload.clinicjs.org/public/44160d0dd4daff7c126bcd47e9635e6b09d318a5f52467d50e36a4e2e8c3cad1/15203.clinic-flame.html#selectedNode=193&zoomedNode=&exclude=83c0&merged=true)

Running 1,000,000 iterations went from 15.67s to 10.09s. That’s a 35% reduction already.

> I know I suggested memoization, and I still don't think it's a bad idea, but I had another idea that I think should be investigated first.
>
> We should be making sure that the hot path (buildSrc and child functions) are all able to be optimized by Node's JIT compiler. If the functions are not being optimized, we could be seeing a slowdown of 3-5x (based on a quick google search). This will improve both server-side rendering (Node) and client-side rendering (Chrome implements a lot, if not all, of the same optimizations).

I don’t have much experience with optimizing the the node runtime. From what I’ve read there are some known "speed killers" and I will need to look more into that. I’m open to any suggestions 😄 

> Regarding the memoization:
> 
> Firstly, I just wanted to clarify this statement: "processing the same urls over and over while it’s running". Do you mean this as in across separate requests from different users/pages? I agree with this, but if it was more "the same urls _in the same request_", then I'd be interested to see how true this was in the real world.

Yeah I mean across separate requests. Memoizing will mean the first request for a page will be slow but the subsequent requests will benefit from the memoization. Not sure if the other scenario is a valid case for memoization.

> I think the first option to implement memoization internally makes more sense. Also, I think that per-component makes the most sense, which is what we've reverted to in the past, as you can easily make a "global" setting using the per-component prop:
> 
> ```js-jsx
> // index.js
> const ImgixWithMemoization = (props) => <Imgix memoize {...props} />;
> 
> // component
> const Header = (props) => (
> <div>
>   ...
>   <ImgixWithMemoization ... />
> </div>
> );
> ```
> 
> Also, we should discuss whether we want to just have memoization on the server-side, or both for the client and server.

I think if we go for the prop approach then we should just leave it up to the user to figure out how to enable memoizing only on the server, right?

**Comment by baldurh** [comment]
I’m not sure if this is still relevant. After some tweaks we’ve managed to increase performance quite substantially!

Comparing 577cc3c43de2c18d0da8ef92e18808bb7e8f10e9 with current master:
Benchmarks in ms, 10,000 iterations

|                                       | before | after | change  | speed increase |
|---------------------------------------|-------------|------------|---------|----------------|
| responsive                            | 8079.423    | 86.506     | -98.93% | 9239.73%       |
| responsive with fixed height          | 2246.772    | 67.552     | -96.99% | 3225.99%       |
| responsive with aspect ratio          | 9838.162    | 102.88     | -98.95% | 9462.75%       |
| fixed width                           | 2255.895    | 66.552     | -97.05% | 3289.67%       |
| fixed width with quality              | 2304.49     | 67.253     | -97.08% | 3326.60%       |
| fixed width with dpr quality disabled | 1958.656    | 62.882     | -96.79% | 3014.81%       |
| fixed width with aspect ratio         | 2257.419    | 63.186     | -97.20% | 3472.66%       |

**Comment by sherwinski** [comment]
This is incredible, awesome job @baldurh!
Personally I'm curious just to see what further improvements memoization will bring so long as it doesn't require too much overhead. But if it's not worth the trouble, then I'm pretty happy with the current state of things 👍

**Comment by baldurh** [comment]
I don’t see any reason to add memoization currently. I’m closing this and we’ll just revisit this later if we think it’s worth it. @sherwinski when can we expect the latest changes to be released? 😁

**Comment by jayeb** [comment]
Hey @baldurh! Sherwin actually left for vacation last week (according to the latest reports he's currently high-fiving exotic wildlife on an archipelago in the Pacific) and in all of the hubbub leading up to it this seems to have slipped through the cracks. Sorry about that! I published a new release this morning with your last four perf improvements so you should be off to the races now 👍.
