### ISSUE TITLE
The example codesandbox doesn't look very good, is stretching the image

### ISSUE THREAD

**Issue by daletom** [imgix/react-imgix#453]
The codesandbox is showing a  stretched version of the blueberry image.  This is because the css is asking for width and height of 200px, but the image is a tall skinny image.  If we don't correctly crop the image, it stretches.  I would propose modifying the index.js file like this: 

```
<div className="App">
      <Imgix src="https://assets.imgix.net/examples/pione.jpg" sizes="200px" imgixParams={{ fit: "crop", ar: "1:1" }} />
    </div>
```

That would correctly crop the image.  It would also serve the correct size image.

**Comment by sherwinski** [comment]
Good catch @daletom! The codesandbox should now be updated.
