### ISSUE TITLE
FindDOMNode is deprecated in StrictMode

### ISSUE THREAD

**Issue by tstirrat15** [imgix/react-imgix#475]
I suppose the first question is what `onMounted` supports. It seems like it breaks React abstractions to some degree. I wasn't able to find discussion on its genesis, either.

I've been working through fixing StrictMode issues in my own project, and `findDOMNode` in this library is one of the things it's complaining about. If `onMounted` is critical functionality, it should be implemented with `ref`s. If it's not, can it be deprecated?

I'll submit a PR.

**Comment by frederickfogerty** [comment]
Ahhhh this is one from a while ago, but I believe the reason it was implemented was so that developers could hook into the root img tag and say, add a `onLoad` handler for their own use. 

We could also probably use a ref here instead of a callback.

```js
// In consuming code...
<Imgix
  ref={(img: HTMLImageElement) => {}}
/>
```

Leaving the rest up to you @sherwinski @jayeb
