### ISSUE TITLE
Support contributors by displaying them in README.md using all-contributors bot

### ISSUE THREAD

**Issue by frederickfogerty** [imgix/react-imgix#477]
**Before you submit:**

- [x] Please search through the existing issues (both open AND closed) to see if your feature has already been discussed. Github issue search can be used for this: https://github.com/imgix/react-imgix/issues?utf8=%E2%9C%93&q=is%3Aissue
- [x] Please take a moment to find out whether your idea fits with the scope and aims of the project

**Is your feature request related to a problem? Please describe.**
Contributors are extremely important in open-source software. This project has been fortunate enough to have many contributors who have elevated every aspect of the code, documentation, and support far above and beyond what imgix and I could have done ourselves.

**Describe the solution you'd like**
Contributors should be prominently recognised in the README (ideally at the top) by using the [all-contributors bot](https://allcontributors.org/).

**Describe alternatives you've considered**
The all contributors project also has a CLI, but it seems like more work than the bot.

Another alternative is to keep the contributors list we have at the moment, but this isn't very rewarding for contributors.

**Additional context**
I'd like to loop in some big contributors like @modosc, @baldurh, and @theolampert for their thoughts.

**Comment by sherwinski** [comment]
Love the idea @frederickfogerty. I'll add it to my list.

But does this mean that @renovate-bot has to be at the top of the list? /s

**Comment by sherwinski** [comment]
Hey @frederickfogerty, the all-contributors bot should now be installed. Feel free to use this thread to add anyone for their specific contributions.

Contribution types can be found here: https://allcontributors.org/docs/en/emoji-key

**Comment by sherwinski** [comment]
@all-contributors please add @baldurh for code

**Comment by frederickfogerty** [comment]
Thanks @sherwinski, I'll close this issue now 👍

**Comment by frederickfogerty** [comment]
@all-contributors add @sherwinski for code, documentation, maintenance, and questions
@all-contributors add @frederickfogerty for code, documentation, maintenance, and questions
@all-contributors add @jayeb for code, documentation, maintenance, and questions
@all-contributors add @modosc for code
@all-contributors add @paulstraw for maintenance
@all-contributors add @theolampert for code
@all-contributors add @rbliss for code and tests
@all-contributors add @ekosz for code and docs
@all-contributors add @tstirrat15 for code
@all-contributors add @samuelgiles for docs
@all-contributors add @rexxars for docs
@all-contributors add @nickhavenly for code
@all-contributors add @minfawang for code
@all-contributors add @kochis for code
@all-contributors add @kellysutton for maintenance
@all-contributors add @enagorny for docs
@all-contributors add @dennisschaaf for code
@all-contributors add @danielfarrell for docs
@all-contributors add @andykent for code
@all-contributors add @GLosch for code

**Comment by frederickfogerty** [comment]
RIP 💀

**Comment by frederickfogerty** [comment]
@all-contributors add @sherwinski for code, documentation, maintenance, and questions

**Comment by frederickfogerty** [comment]
@all-contributors add @frederickfogerty for code, documentation, maintenance, and questions

**Comment by frederickfogerty** [comment]
Right... all-contributors seems to make a new PR for each comment. This could be a long process

**Comment by frederickfogerty** [comment]
@all-contributors add @sherwinski for code, documentation, maintenance, and questions, and add @frederickfogerty for code, documentation, maintenance, and questions

**Comment by sherwinski** [comment]
Seems that other people have expressed interest in a feature for adding multiple contributors at once: https://github.com/all-contributors/all-contributors-bot/pull/127

For now I think we will have to resort to doing it one by one 🙁

**Comment by sherwinski** [comment]
Ok, let's try this again. Sorry in advance for the spam 🙊 

@all-contributors add @sherwinski for code, documentation, maintenance, and questions

**Comment by sherwinski** [comment]
@all-contributors add @frederickfogerty for code, documentation, maintenance, and questions

**Comment by sherwinski** [comment]
@all-contributors add @jayeb for code, documentation, maintenance, and questions

**Comment by sherwinski** [comment]
@all-contributors add @modosc for code

**Comment by sherwinski** [comment]
@all-contributors add @paulstraw for maintenance

**Comment by sherwinski** [comment]
@all-contributors add @theolampert for code

**Comment by sherwinski** [comment]
@all-contributors add @rbliss for code and tests

**Comment by sherwinski** [comment]
@all-contributors add @ekosz for code and docs

**Comment by sherwinski** [comment]
@all-contributors add @tstirrat15 for code and bugs

**Comment by sherwinski** [comment]
@all-contributors add @samuelgiles for docs

**Comment by sherwinski** [comment]
@all-contributors add @rexxars for docs

**Comment by sherwinski** [comment]
@all-contributors add @nickhavenly for code

**Comment by sherwinski** [comment]
@all-contributors add @minfawang for code

**Comment by sherwinski** [comment]
@all-contributors add @kochis for code

**Comment by sherwinski** [comment]
@all-contributors add @kellysutton for maintenance

**Comment by sherwinski** [comment]
@all-contributors add @enagorny for docs

**Comment by sherwinski** [comment]
@all-contributors add @dennisschaaf for code

**Comment by sherwinski** [comment]
@all-contributors add @danielfarrell for docs

**Comment by sherwinski** [comment]
@all-contributors add @andykent for code

**Comment by sherwinski** [comment]
@all-contributors add @GLosch for code

**Comment by sherwinski** [comment]
There we go 😤
