### ISSUE TITLE
Include performance benchmarks in test suite

### ISSUE THREAD

**Issue by sherwinski** [imgix/react-imgix#480]
- [x] Please search through the existing issues (both open AND closed) to see if your feature has already been discussed. Github issue search can be used for this: https://github.com/imgix/react-imgix/issues?utf8=%E2%9C%93&q=is%3Aissue
- [x] Please take a moment to find out whether your idea fits with the scope and aims of the project

**Is your feature request related to a problem? Please describe.**
I was really impressed with @baldurh's performance benchmarks ([see example](https://github.com/imgix/react-imgix/issues/405#issuecomment-515919763)) and was wondering if there was someway that similar tooling could be added into this project's tests. I think for users who are concerned with performance, it would provide a reliable way to see the before and after effects of their changes.

**Describe the solution you'd like**
A set of tests in a performance directory (similar to `unit` or `integration`) that can be run with karma. Initially, it can provide some benchmarks for the cases listed in comment I linked earlier. We could take it further by automatically running the same benchmarks in a feature branch and comparing against the base branch.

I've done a decent amount of research into this to see what are the viable options for a React project. Some options worth exploring are: [React Profiler API](https://reactjs.org/docs/profiler.html), [User Timing API](https://www.telerik.com/blogs/profiling-react-components-with-the-user-timing-api), and [benchmark.js](https://benchmarkjs.com/). I'm sure there could be others as well. Sources online have also pointed to `react-addons-perf`, but as of React 16 it is no longer supported.

**Describe alternatives you've considered**
The same idea could be achieved by generating flamegraphs manually, but ideally I would want to automate this and include it as part of the test run.

**Additional context**
I'm open to different ideas and discussion about how to achieve this. Perhaps @baldurh can weigh in on his specific set up and how it might integrate into the project?

**Comment by baldurh** [comment]
My setup wasn’t nice at all 😅 I basically added an export for the functions I wanted to benchmark, built the code and ran a script with a timer and a bunch of for loops

**Comment by sherwinski** [comment]
@baldurh Good to know! Perhaps an example of the best approach being the most straightforward one.

**Comment by sherwinski** [comment]
Closing as this issue is quite old and there hasn't been any movement on it.
