### ISSUE TITLE
How do I use the "gif-q" parameter?

### ISSUE THREAD

**Issue by wfendler** [imgix/react-imgix#524]
Animated gifs have a separate parameter `gif-q` to control quality. How is this param passed to the `<Imgix />` component?

**Comment by sherwinski** [comment]
Hey @wfendler, any parameters can be passed to the component via the `imgixParams` prop regardless of the image file type. For example:
```js
<Imgix
	src={src}
	imgixParams={{ gif-q: "30" }}
/>
```
Hopefully this helps answer your question. If you have any further questions about usage, feel free to write in to our support line at support@imgix.com

**Comment by sherwinski** [comment]
I should also mention that the `gif-q` parameter works in the opposite way to our image quality parameter. For animated gifs, a higher `gif-q` value would result in more compression. In the case of images, a higher `q` value would result  in less compression.

**Comment by joshpetit** [comment]
Hey @sherwinski, I tried using this parameter as:

```tsx
<Imgix
	src={src}
	imgixParams={{ 'gif-q': "30" }}
/>
```
and get an error that that property `gif-q` doesn't exist. Is this still a valid option?

**Comment by sherwinski** [comment]
@joshpetit Apologies, I totally missed your message 🤦 

What type of error is it? I assume it's being thrown by TypeScript since `imgixParams` allows users to pass any key/value pairs without any sort of validation.

**Comment by joshpetit** [comment]
@sherwinski No problem at all! Ok I see, so is there no way around this? I was particularly trying to do this since gifs aren't playing, so I was thinking that changing the quality might fix it. This might be an entirely separate issue though.

**Comment by sherwinski** [comment]
@joshpetit Yeah it sounds like a separate issue. I would encourage you to send a message over to support@imgix.com about this, as your account might not have the correct settings enabled.

**If** you do end up wanting to use `gif-q` after resolving that, you may need to add a ts-ignore comment before that line. This is because it's not an official parameter according to the DefinitelyTyped definition:

```js
<Imgix
	src={src}
	//@ts-ignore
	imgixParams={{ 'gif-q': "30" }}
/>
```

**Comment by joshpetit** [comment]
@sherwinski I appreciate it! Thank you
