### ISSUE TITLE
Warn if `src` is not an imgix URL

### ISSUE THREAD

**Issue by jackfranklin** [imgix/react-imgix#527]
**Before you submit:**

- [x] Please search through the existing issues (both open AND closed) to see if your feature has already been discussed. Github issue search can be used for this: https://github.com/imgix/react-imgix/issues?utf8=%E2%9C%93&q=is%3Aissue
- [x] Please take a moment to find out whether your idea fits with the scope and aims of the project

**Is your feature request related to a problem? Please describe.**

I've found myself trying to debug why Imgix isn't working for us before realising that I've done `<Imgix src={"cloudfront url to an img"} />` rather than passing in the URL to our `*.imgix.net` domain.

**Describe the solution you'd like**

In development pod, react-imgix could inspect the `src` prop that is has been given and warn if it's not a `*.imgix.net` domain.

I'm happy to do the work here and make the PR but wanted to see what you thought and if you'd be willing to have a change like this :)

**Comment by sherwinski** [comment]
Hey @jackfranklin thanks for the suggestion! As much as I think this would be a useful addition, there is unfortunately no way for us to be certain that a URL is an imgix URL based on the hostname alone. Users are able to (and many do) set custom domains that deviate from the `*.imgix.net` format.
If you ever have other ideas/suggestions, definitely feel free to open another issue or a PR 😀
