### ISSUE TITLE
any plans to support the <picture> element?

### ISSUE THREAD

**Issue by modosc** [imgix/react-imgix#55]
is supporting `<picture>` in the roadmap at all?

i've hacked this together locally using [processImage](https://github.com/imgix/react-imgix/blob/master/src/support.js) but i'm guessing that's not meant for public consumption. i could try to put a pr together but i'm still sorting through what the api would look like..

**Comment by frederickfogerty** [comment]
Hey @modosc. Currently I'm not working with react-imgix, so it would be up to @paulstraw at this stage.

**Comment by paulstraw** [comment]
@modosc That'd be great! Since I don't use React on a daily basis, it would be awesome to get some thoughts from you on idiomatic approaches, etc.

**Comment by modosc** [comment]
sure - here's what i came up with in my iterations. 

one option would be to have a `source` prop to just return a `<source>` element, then combined with a `media` prop you could roll the `<picture>` element on your own:

```
<picture>
  <Imgix source media='min-width: 400px' {...{width, height, src, etc}}/>
  <Imgix source media='min-width: 800px' {...{width, height, src, etc}}/>
  {/* this is our default img element for browsers without <picture> support */}
  <Imgix {...{width, height, src, etc}}/>
</picture>
```

another would be to take multiple `srcs` as a prop and generate the above from them:
```
const srcs = [
  { minWidth: 400, src: someUrl, width: 400, height },
  // default: true means that we use this data to also build our default <img> element
  { minWidth: 800, src: someUrl, width: 800, height, default: true }, 
]

<Imgix picture {...srcs} {...{otherOptions}}/>

```

the advantage here is that the props passed into `<Imgix>` could be used as defaults - this way you only have to specify what's different in `srcs`. it's still kind of a kludgy api though but this is how my current hacky solution works. 

but ideally i'd like a solution like this: 
```
<Imgix picture {...someProps}>
  <Imgix source src={someOtherUrl} minWidth={300}/>
  <Imgix source src={anotherUrl} minWidth={600}/>
</Imgix>
```
here the children would pick up the parent props as defaults.  the parent props could also be used to build the default `<img>` tag - this way even without any `<source>` elements you still get a viable `<picture>` element. and if you need to you'd be able to roll your own like my initial example. 

i'm also making the assumption that `min-width` is the media query that people would use most - theoretically you could use anything here but i haven't seen any examples using anything else. i suppose supporting a generic `media` prop would be necessary. 

probably [type](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture#Example_2_Using_the_type_attribute) wouldn't be needed though since `auto` formatting should handle that for us?

**Comment by frederickfogerty** [comment]
I like the last solution. I'm just wondering if we consider creating `ImgixPicture` and `ImgixSource` components, or we use props, such as in the proposed solution.

I think my preference would be to use props, but been to hear your thoughts @modosc

**Comment by modosc** [comment]
another way would be to export the `Picture` and `Source` classes as static properties of the `Imgix` class - you could access them via `<Imgix.Picture>` / `<Imgix.Source>` ( [react-bootstrap](http://react-bootstrap.github.io/components.html#forms-controls) uses this pattern). it's not super great because it mostly bypasses tree-shaking and can break some optimizations. 

i like the prop method though because there's already a `bg` prop that changes the component returned (and adds additional inline styles) so there is precedent. plus it's much easier to use and (to me at least) feels more idiomatic.

**Comment by frederickfogerty** [comment]
Thoughts on maybe exposing picture and source through a `type='bg | img | picture | source'` property?

**Comment by modosc** [comment]
i like `type='bg | img | picture | source'` - would still have to support the `bg` prop but maybe we could print some deprecation notice about it going forward.

i think this is enough to start with, thanks!

**Comment by paulstraw** [comment]
Reading through all this, sounds like you've reached something good. I like the `type='bg | img | picture | source'` idea.

**Comment by modosc** [comment]
one other thing - how would/does this work with the `component` prop? seems like `type` would have to override that in all cases except `bg` so maybe that's the only time when it's respected?

**Comment by frederickfogerty** [comment]
I think `component` would still act as an override - in the documentation it is specified as an override. If the user wants to use another tag with a `picture` configuration, they should be able to do that. It would be useless to do that, but I think it's important to give that control.

**Comment by modosc** [comment]
fair enough. i've got some work going on this today, hopefully i'll have something to show soonish.

**Comment by frederickfogerty** [comment]
Awesome @modosc!

**Comment by modosc** [comment]
see #60
