### ISSUE TITLE
ssr broken when using bg

### ISSUE THREAD

**Issue by modosc** [imgix/react-imgix#56]
when we use server-side rendering and disable client-side js we get an empty `background-image` tag. this is fixed by enabling `aggressiveLoad`.

we don't see the same issue without `bg`, those images load fine. 

i think either the docs should be updated to explain this or `aggressiveLoad` should be implicitly enabled when using `bg`, not sure which?

**Comment by modosc** [comment]
oops i take it back - i can't confirm that things work without `bg` since right now i'm using my hacked version rather than `<Imgix>` directly. so maybe just updating the docs to use `aggressiveLoad` when doing SSR is ok?

**Comment by paulstraw** [comment]
Thaks @modosc, I just added a note about this to the readme.
