### ISSUE TITLE
js-base64 uses eval, leading to CSP violations

### ISSUE THREAD

**Issue by junoatscroll** [imgix/react-imgix#565]
When using react-imgix on a site with Content Security Policy, one of react-imgix's dependencies triggers CSP violations by using eval. 

From Chrome dev tools:
```
base64.js:30 [Report Only] Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "default-src https: 'unsafe-inline'". Note that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.
```

The offending line looks like it's feature detecting nodejs:
https://github.com/dankogai/js-base64/blob/e8a9a09edaf79fddee3623d97421151dcbd384c9/base64.js#L30

Further, a base64 library should not be needed in a browser environment, which has `atob()` and `btoa()` available. The fallback library could be loaded in a node environment if or native base64 support were not available.

**Describe the solution you'd like**
A build of react-imgix that does not use eval.

**Describe alternatives you've considered**
- Forking react-imgix to meet our needs. This is undesirable because we'd lose out on updates and other enhancements in react-imigx, and have to maintain additional 3rd party libraries.

- Bundling react-imgix but stubbing out js-base64. This is still undesirable because we'd have to modify other parts of our build and dependency management chain to accommodate this exception.

**Comment by sherwinski** [comment]
Thanks for bringing this to our attention @junoatscroll! I think your proposed solution of using the fallback library outside of the browser environment should work. I'll look into creating a patch at some point this week 👍

**Comment by ericdeansanchez** [comment]
Hey 👋  @junoatscroll thanks for opening this issue. I'm new to the team and I'm going to be taking a look at this. Also thank you for posting a link to the offending line, I _really_ appreciate that.
