### ISSUE TITLE
"No fallback <img /> or <Imgix />" warning always shown

### ISSUE THREAD

**Issue by gslama-akqa** [imgix/react-imgix#577]
I'm always getting the following error 
`"No fallback <img /> or <Imgix /> found in the children of a <picture> component. A fallback image should be passed to ensure the image renders correctly at all dimensions."

By looking the code, it seems the condition `c.type === ReactImgixWrapped` is never satisfied. Using `c.type.displayName === ReactImgixWrapped.displayName` worked though.

I'm not sure why it is working as expected with the displayName but would happily open a PR if this change is considered satisfying.

Attaching a couple of screenshot for demonstration purpose.

<img width="1552" alt="Screenshot 2020-03-18 at 14 49 21" src="https://user-images.githubusercontent.com/43370823/76968128-acfb9a80-6928-11ea-91f7-70163a7f2fd3.png">
<img width="1552" alt="Screenshot 2020-03-18 at 14 55 43" src="https://user-images.githubusercontent.com/43370823/76968148-b127b800-6928-11ea-8683-1d4394d1207e.png">

**Comment by ericdeansanchez** [comment]
Closing this issue for now. @gslama-akqa if you have any more questions please feel free to comment here (and I'll reopen this). Also feel free to open a new issue for any further comments, questions, or concerns. Thank you! :)
