### ISSUE TITLE
Using signed urls with the <Imgix /> component

### ISSUE THREAD

**Issue by Cali93** [imgix/react-imgix#580]
**Before you submit:**

- [x] Please search through the existing issues (both open AND closed) to see if your question has already been discussed. Github issue search can be used for this: https://github.com/imgix/react-imgix/issues?utf8=%E2%9C%93&q=is%3Aissue

**Question**
A clear and concise description of your question

Hi, I've been trying to implement secure urls in combination with the react-imgix library. But I'm experiencing some issues.

I thought it would be as straight forward as making a request to our server that would sign the request and send back the signed src along with the src set.

However, when I pass in the secure src to the Imgix component, it appends extra params after the "s" param. Like so: s=df3493c41316c15e91210xxxxcbd72c&auto=format&w=320

Here is my component: 
```js
const Image: React.FC<{ alt: string; srcSet: string } & SharedImigixAndSourceProps> = ({
	width,
	src,
	srcSet,
	className,
	alt,
	htmlAttributes,
	...rest
}) => {
	return (
		<Imgix
			className={cx('lazyload', className)}
			width={width}
			src={src}
			disableLibraryParam={true}
			attributeConfig={{
				src: 'data-src',
				srcSet: 'data-srcset',
				sizes: 'data-sizes',
			}}
			htmlAttributes={{
				src,
				srcSet, // I tried with and without it
				alt,
				...htmlAttributes,
			}}
			{...rest}
		/>
	);
};`

**Comment by ericdeansanchez** [comment]
Hey @Cali93 👋 sorry for such a delayed response, but securing URLs does not require you to make any requests to any server.

Officially, the way URL signing works is
>To secure an image URL, we use a cryptographic hash function called "MD5" to combine the original URL with your source's unique, secure token: {YOUR TOKEN}. The result of this hash function is then appended to the end of your unsigned URL with the s parameter, creating a signed URL.

>If the path or parameters of your URL are altered after the s parameter has been set, the altered URL will return a "404 Not Found" code instead of an image. This prevents unauthorized parties from changing the parameters on your URLs, but it also means that if you need to change the parameters yourself, you'll need to re-sign the new URL.

**Comment by sherwinski** [comment]
Hey @Cali93, to add to that you may want to utilize the [`disableSrcSet`](https://github.com/imgix/react-imgix#disablesrcset--bool-default--false) prop. That way, the component will not append extra parameters when generating your `srcset` list. Also, it may be helpful for you to use a library such as [imgix-core-js](https://github.com/imgix/imgix-core-js#imgixclientbuildsrcsetpath-params-options) to generate a signed `srcset` list server-side and pass that directly into the `srcset` attribute on the component. Hope that helps.

**Comment by frederickfogerty** [comment]
Hey @Cali93 👋 Fred here - creator of this library. I added some more of my thoughts about this issue in @ericdeansanchez's response. Hope this helps!

**Comment by ericdeansanchez** [comment]
Thanks @frederickfogerty !!!

**Comment by Cali93** [comment]
Thank you for your answers @frederickfogerty @ericdeansanchez @sherwinski. I ended up using the approach recommended by @frederickfogerty and it works like a charm. That's what I was already planning to do if the react Imgix component wasn't compatible with secure urls.

**Comment by ericdeansanchez** [comment]
That's awesome! Glad to hear things worked out!
