### ISSUE TITLE
onError Function or Fallback for Image Load Errors (404)

### ISSUE THREAD

**Issue by Adrianjs42** [imgix/react-imgix#595]
Similar to this Issue [#157 ](https://github.com/imgix/react-imgix/issues/157) I need support for an onError Function to check the Status Code of the response. If the requested image is not found (404) the onError function should be fired and I could add a fallback image or try another one in the array.

In the best case we could also adress the onLoad and other events:

```
onError={() => this.loadImage(true)}
onLoad={this.loadImage.bind(this)}
```
Example of usage:
```
<Picture>
  <Source
    src={`https://xxx.imgix.net/${imageName}`}
    width={500}
    htmlAttributes={{
      media: '(min-width: 0px)',
      className: 'lazyload img-fluid',
    }}
    imgixParams={{
      fit: 'crop',
      ar: '16:9',
    }}
  />
  {/* Fallback */}
  <Imgix
    className="img-fluid lazyload"
    src={`https://xxx.imgix.net/${imageName}`}
    imgixParams={{
      fit: 'crop',
      ar: '16:9',
      width: 200,
    }}
   onError={() => this.loadAnotherImage(true)}
  />
</Picture>
```
- react-imgix version: [9.0.1]

**Comment by frederickfogerty** [comment]
Hi @Adrianjs42! Fred from @imgix here. Thank you for opening an issue! Fortunately, we support a (not well documented) feature called `htmlAttributes` which can be used for this kind of custom behaviour. This prop will pass attributes straight down the html element.

In your specific case, it might look like this:

```jsx
  <Imgix
    className="img-fluid lazyload"
    src={`https://xxx.imgix.net/${imageName}`}
    imgixParams={{
      fit: 'crop',
      ar: '16:9',
      width: 200,
    }}
    htmlAttributes={{
      onError: () => this.loadAnotherImage(true),
      onLoad: () => {} // whatever you'd like! :)
    }}
  />
```

Please let us know how this goes for you. I'm going to close this for now but please feel free to follow up if you have any more issues here! 😄
