### ISSUE TITLE
Transition for lazyloaded images

### ISSUE THREAD

**Issue by goellner** [imgix/react-imgix#650]
Is it possible to add a simple fade transition for lazyloaded images, currently it replaces the image once it loaded and it would be nice to add a small transition to make the experience smoother.

**Comment by frederickfogerty** [comment]
Hey there @goellner, Fred from imgix here 👋 thanks for reaching out!

I love the idea, but unfortunately it is just not possible for us to implement this given our current architecture. Currently our lazy-loading support in this library is achieved through third-party libraries. We recommend using [lazysizes](https://github.com/aFarkas/lazysizes) but the user is free to choose their own library as they please. Thus, I hope it's clear how it's impossible for us to implement this.

However, not all hope is lost! If you are using lazysizes, there is a [whole section](https://github.com/aFarkas/lazysizes#lqipblurry-image-placeholderblur-up-image-technique) on the LQIP/blur-up technique, and it even seems like there is a [dedicated blur-up plugin](https://github.com/aFarkas/lazysizes/tree/master/plugins/blur-up) that should support your use case.

I'm going to close this out for now, but feel free to comment again if you have any more questions!
