### ISSUE TITLE
How can I get auto=format,compress

### ISSUE THREAD

**Issue by jodiedoubleday** [imgix/react-imgix#655]
**Before you submit:**

- [x] Please search through the existing issues (both open AND closed) to see if your question has already been discussed. Github issue search can be used for this: https://github.com/imgix/react-imgix/issues?utf8=%E2%9C%93&q=is%3Aissue

**Question**
We have `auto=format` by default, how can i pass in `auto=format,compress`?
I can't see anything in the documentation but I have found people using...
`<Imgix auto={['format', 'compress']}`
but this doesn't seem to work for me.

**Comment by ericdeansanchez** [comment]
Hey 👋  @jodiedoubleday thanks for opening this issue! Which version of `react-imgix` are you using?

In `ixlib=react-9.0.2`, or react-imgix (ix) version `9.0.2`, the above can be achieved by:

```jsx
import React from "react";
import ReactDOM from "react-dom";
import Imgix from "react-imgix";

import "./styles.css";

function App() {
  return (
    <div className="App">
      <Imgix
        src="https://assets.imgix.net/examples/pione.jpg"
        sizes="200px"
        imgixParams={{ fit: "crop", ar: "1:1", auto: "format,compress" }}
      />
    </div>
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```
A live demo of the code above can be found [here](https://codesandbox.io/s/mystifying-sun-lt4jc?file=/src/index.js) and the `src={url}` that the above ultimately generates is:

```html
<!-- The "url" in `src={url}` from above -->
https://assets.imgix.net/examples/pione.jpg?auto=format%2Ccompress&fit=crop&ar=1%3A1&ixlib=react-9.0.2
```

If you're using a different version of `react-imgix`, just let me know and we'll find something that works

**Comment by ericdeansanchez** [comment]
Hello again 👋  @jodiedoubleday I just wanted to be sure I've answered your question completely. If you have any more questions please feel free to follow up here and/or open another issue.
