### ISSUE TITLE
"No fallback <img /> or <Imgix /> found in the children of a <picture> component" with styled-components

### ISSUE THREAD

**Issue by yuyaohshimo** [imgix/react-imgix#698]
**Describe the bug**
`No fallback <img /> or <Imgix /> found in the children of a <picture> component` is showed when a component is wrapped within styled-components.

**To Reproduce**
[Here](https://codesandbox.io/s/dazzling-cartwright-37r9b?fontsize=14&hidenavigation=1&theme=dark) is a link to codesandbox.

**Comment by frederickfogerty** [comment]
Hi @yuyaohshimo, thank you for the bug report and the CodeSandbox example.

Although I agree that this is technically a bug, it seems that the impact on our users is small so this is a low priority. I've added this to our internal list of improvements and we will hope to address this at some point.

In the meantime, the workaround I recommend is to disable the fallback image warning as documented in the [Global Configuration](https://github.com/imgix/react-imgix#global-configuration) section in the readme.

Thanks!
