### ISSUE TITLE
How do you use LQIP & lazysizes (documentation misses some things)

### ISSUE THREAD

**Issue by agcty** [imgix/react-imgix#717]
**Question**

How do you actually implement a working LQIP image?

I've got the following code:

```javascript
const previewURL = buildURL(
    `${process.env.NEXT_PUBLIC_IMGIX_URL}/${getImgixPathFromSignedUrl(
      template?.preview
    )}`,
    { q: 70 }
  );


 <Imgix
          className="object-contain mx-auto my-4 mb-8 rounded-lg shadow-lg lazyload"
          alt={template.name}
          src={previewURL}
          sizes="100vw"
          htmlAttributes={{ style: { maxHeight: "55vh" }, src: previewURL }}
          attributeConfig={{
            src: "data-src",
            srcSet: "data-srcset",
            sizes: "data-sizes",
          }}
        />
```

```javascript
import lazysizes from "lazysizes";
import "lazysizes/plugins/attrchange/ls.attrchange";
import "lazysizes/plugins/blur-up/ls.blur-up";

lazysizes.cfg.blurupMode = "always";
```

Here's a video of the issue:

https://shareit.video/h6eP1jG4GNEr7vwroM5b

Basically it doesn't load the low res placeholder for whatever reason and what's more important the image doesn't even show up until after the component has rendered and I'm not sure why. Is there a working ( & recent) code sample anywhere?

**Comment by luqven** [comment]
There hasn't been any movement on this issue for some time so I'm going to go ahead and close it. If you're still having an issue/have a question, please comment and I'll be sure to re-open it.

FWIW, I think the issue above stemmed from use of the `src` prop for the LQIP:

```diff
--    src={previewURL}
++   htmlAttributes={{
    src: previewURL
  }}
```

If you're looking for our LQIP documentation, read [here](https://github.com/imgix/react-imgix#low-quality-image-placeholder-technique-lqip) for more details.
