### ISSUE TITLE
How to use the LQIP loading technique with fade in?

### ISSUE THREAD

**Issue by michaelmarconi** [imgix/react-imgix#739]
Hi — I've followed the instructions to use the LQIP loading technique at https://github.com/imgix/react-imgix#low-quality-image-placeholder-technique-lqip, which is working, however there is no transition between the low quality image and the final image, which is jarring.

I'd like to use the blur plugin that is referenced in the lazysize library (see:  https://github.com/aFarkas/lazysizes/tree/master/plugins/blur-up), which states that I should:

> Simply add a data-lowsrc attribute with the low quality image placeholder image to your img

I've tried a couple of things, including the code below, but nothing seems to activate the blur effect.  Does anyone have any idea how to make this work please?

```jsx
      <Imgix
        src={`https://[REDACTED].imgix.net/${imagePath}`}
        sizes={sizes}
        className={`lazyload ${className}`}
        attributeConfig={{
          src: "data-src",
          srcSet: "data-srcset",
          sizes: "data-sizes",
        }}
        htmlAttributes={{
          src: `https://[REDACTED].imgix.net/${imagePath}?auto=format&blur=200&px=16&w=150`,
          "data-lowsrc": `https://[REDACTED].imgix.net/${imagePath}?auto=format&blur=200&px=16&w=150`,
        }}
      />
```

**Comment by frederickfogerty** [comment]
Hey @michaelmarconi, thank you for opening this issue. Are you able to confirm if the `data-lowsrc` attribute is correctly set in the HTML? 

FYI, you might want to redact your imgix url on the `src: ` line too.

**Comment by michaelmarconi** [comment]
Hi @frederickfogerty — thanks, I've redacted the part I missed!

I can confirm that `data-lowsrc` is correctly set in the HTML.  I'll cross-post this to _lazysizes_ and see if they have any ideas..

**Comment by frederickfogerty** [comment]
Great, please let us know how it goes! This is good learning for us too.

**Comment by frederickfogerty** [comment]
I'm closing this for now since there's nothing actionable on our side.
