### ISSUE TITLE
Support for Mask API

### ISSUE THREAD

**Issue by moaazsidat** [imgix/react-imgix#75]
Hey @frederickfogerty, just wondering if this supports the [imgix Mask API](https://docs.imgix.com/apis/url/mask/mask)? 

Doesn't seem to be documented in the `props`, or maybe I'm missing something?

**Comment by frederickfogerty** [comment]
Hey @moaazsidat. You're right, it does not support it formally. You can try passing mask options using `customProps`, but I can't guarantee it'll work

```
<Imgix
  customProps={{
    mask: // don't know how mask options work
  }}
/>
```

**Comment by theolampert** [comment]
@moaazsidat I think @frederickfogerty mean to refer to `customParams` not `customProps`. I had a quick look and was able to get this work by doing the following:
```js
<Imgix
  customParams={{
    mask: 'ellipse'
  }}
/>
```

However I wasn't able to pass any further options to the custom parameter eg `ellipse&w=250&h=250` does not work. This looks to be an issue with how `jsUri` is used

**Comment by theolampert** [comment]
@frederickfogerty maybe this can be closed if we add an example under `customParams` in the readme? I can make a PR for this if you like.

**Comment by frederickfogerty** [comment]
That would be great @theolampert

**Comment by theolampert** [comment]
@frederickfogerty done, you can take a look [here](https://github.com/imgix/react-imgix/pull/109)
