### ISSUE TITLE
<Background> generating parameters twice for width and height

### ISSUE THREAD

**Issue by JorgeSivil** [imgix/react-imgix#763]
Based on the code I had to send imgixParams{ w: X, h: Y } to use the forced values.

But this would result in two parameters w and h appended to the URL.

Expected result: Only one parameter should be sent for a given key.

**Comment by sherwinski** [comment]
Hey @JorgeSivil, thanks for bringing this issue to our attention. Our team will look into this and get back to you here. We'd also be happy to accept a PR that fixes this issue if anyone is interested in opening one.

**Comment by ericdeansanchez** [comment]
Reproduced.

Steps to reproduce:
* create react app
* use the `Background` like below:
```jsx
import { Background } from "react-imgix";

function App() {
  return (
    <Background
      src="https://assets.imgix.net/dam-marketing/Updates_2020_Launch/Summer/Image_Tags.png?fm=jpg&q=90&ixlib=imgixjs-3.4.1"
      className="blog-title"
      imgixParams={{ w: 100, h: 100 }}
    >
      <h2>Blog Title</h2>
    </Background>
  );
}

export default App;
```

Options:
* we could change how this works [here](https://github.com/imgix/react-imgix/blob/637da1799a5ba23f8505a87fdaadf19466555366/src/constructUrl.js#L127) (e.g. transform params that need it and letting "the last width/w win")
* there's also this [here](https://github.com/imgix/react-imgix/blob/637da1799a5ba23f8505a87fdaadf19466555366/src/react-imgix-bg.jsx#L29), but...

**Comment by sherwinski** [comment]
We could also deduplicate any `w` and `h` in in [imgixParams](https://github.com/imgix/react-imgix/blob/637da1799a5ba23f8505a87fdaadf19466555366/src/react-imgix-bg.jsx#L93) since we're just going to include a determined [width and height](https://github.com/imgix/react-imgix/blob/637da1799a5ba23f8505a87fdaadf19466555366/src/react-imgix-bg.jsx#L95-L96) right afterwards.

**Comment by ericdeansanchez** [comment]
Yeah, ideally I'd like to set things up in a way where the duplication doesn't happen to begin with. Hmm...
