### ISSUE TITLE
Docs link to wrong CodeSandbox for Flexible Image Rendering

### ISSUE THREAD

**Issue by a-trost** [imgix/react-imgix#787]
**Describe the bug**
The docs in the README provide a link to edit on CodeSandbox, but for the [Flexible Image Rendering](https://github.com/imgix/react-imgix#flexible-image-rendering) section, they link to a different example. 

The code in the docs is:
```js
import "./styles.css";

<div className="App">
  <Imgix
    src="https://assets.imgix.net/examples/pione.jpg"
    sizes="calc(10% - 10px)"
  />
</div>;
```

While the code in the CodeSandbox is:
```js
import "./styles.css";

function App() {
  return (
    <div className="App">
      <Imgix
        src="https://assets.imgix.net/examples/pione.jpg"
        sizes="200px"
        imgixParams={{ fit: "crop", ar: "1:1" }}
      />
    </div>
  );
}
```

Showing off a different feature entirely.

Here is the link to the section of the docs: https://github.com/imgix/react-imgix#flexible-image-rendering

And here is a link to the current code sandbox: https://codesandbox.io/s/charming-keller-kjnsq?file=/src/index.js:95-341

**Comment by frederickfogerty** [comment]
Hey @a-trost, thanks for opening this issue. I don't know where the fluid CodeSandbox got off to, but I've made a new one and updated the link in the associated PR.

**Comment by a-trost** [comment]
Awesome, thanks, @frederickfogerty! That looks great.
