### ISSUE TITLE
Version 9 over-encodes file paths

### ISSUE THREAD

**Issue by jperegoy** [imgix/react-imgix#815]
**Describe the bug**
When given a `src` which already has uri-encoded elements, the library is encoding them a second time, breaking the image path.

**To Reproduce**
Consider a file name saved with spaces: `spaced file.jpg`, which has been saved by/into a cms and encoded to display properly as `spaced%20file.jpg`. When `spaced%20file.jpg` is provided to _react-imgix_, the output shows this percent symbol as encoded, yielding a path of `spaced%2520file.jpg` which does not exist.

**Expected behaviour**
Filenames are not mis-encoded and return an appropriate source.

**Information:**
Downgrading back to `8.6.4` resolves the issue. It appears, though I may be mistaken, that this was introduced in [#780](https://github.com/imgix/react-imgix/pull/780) and the upstream dependency in core-js's [_sanitizePath](https://github.com/imgix/js-core/blob/main/src/index.js#L96) method.

- react-imgix version: Discovered on `9.2.0`
- browser version: `FF DE 93.0b4`

**Comment by ericdeansanchez** [comment]
Hey 👋 thanks for opening this issue. Part of what changed from `8.6.4` to #780  was that file paths are expected to be passed in their unencoded form, e.g. `spaced file.jpg`. However, if you save `spaced file.jpg` and your cms percent-encodes this file path this expectation won't work for you.

> file name saved with spaces: `spaced file.jpg`, which has been saved by/into a cms and encoded to display properly as `spaced%20file.jpg`

Okay, the file is saved with a space in the file name, but the cms percent-encodes this space to be `%20` at some point, correct?

> When `spaced%20file.jpg` is provided to react-imgix

By this point, the cms provides `spaced%20file.jpg` to react-imgix. Could you give an example of how it is provided to the component and which component it is provided to?

**Comment by jperegoy** [comment]
Sure, happy to provide those details.

Specifically we are seeing content editors upload objects with spaced filenames to the Acquia Dam which are then encoded and stored by that system, leaving them with percent-encododed paths. End users of Acquia DAM - and I'd suspect most similar providers - do not have the ability to change this behavior to my knowledge. When we query against an entity which holds that data we are returned the path as a string, e.g. `https://cms-production.site.com/.../file%20name.jpg`.

In some case we do handle this output briefly before passing it to the `src` prop of any of the _react-imgix_ components so that we can check and/or transform the path to use an appropriate _Imgix_ source. Our use case is  overwhelmingly either `<Imgix />` or `<Background />`. Ostensibly - and this worked while troubleshooting - we can decode that filename before passing it to _Imgix_, but it feels like quite the hack to send in a known-incorrect path (`site.com/.../file name.jpg` would 404) to have the core-js restore the correct file name.

It's probably a chore to programmatically decide if a given string is-or-isn't url-encoded on your end, so I'd think it a natural candidate for `imgixParams` as something like `encodeUri: false` being the opt-out.

**Comment by frederickfogerty** [comment]
Hey @jperegoy, Fred from imgix here. Thanks so much for providing some more information. We are going to discuss the possibility of this as a team and will get back to you next week ✌️

**Comment by jperegoy** [comment]
Hey @frederickfogerty, I'm just checking in on this to see if there's been any movement here, as it remains an outstanding issue.

**Comment by sherwinski** [comment]
Hey @jperegoy, we haven't had much movement here as our team has been pretty heads down on two new major projects. We are always happy to review/accept PRs if any one is interested in tackling this in the meantime, as well as talking through designs of how an implementation for this could look.

**Comment by digeverything** [comment]
👋 Thanks for flagging @jperegoy. This is also an issue for my implementation using image URLs coming from the Prismic CMS api, I've pinned at `8.6.4` for now (but wish I could upgrade to take advantage of features/improvements in 9+).

**Comment by frederickfogerty** [comment]
Hey @digeverything, and @jperegoy, we've successfully addressed this in #849. Would you mind taking a look at letting us know what you think of the intended interface and if you have any other feedback? We're looking to merge this in next week.

**Comment by digeverything** [comment]
This looks great to me, I assume this will work with the `ImgixProvider` component? If so, then this will 💯 solve my issue. Thank you for addressing so quickly. Keep up the great work!

**Comment by frederickfogerty** [comment]
@digeverything I will investigate that today and get back to you 👍

**Comment by frederickfogerty** [comment]
@digeverything just to confirm here that this is in fact supported by the provider component as well 👍

**Comment by jperegoy** [comment]
@frederickfogerty Just a bit behind the times here, but this looks great. Thank yous!

**Comment by timscullin** [comment]
This works well for <Imgix> components, but not for <Background>.
Should I submit a new issue or is it better to open this one back up?

**Comment by sherwinski** [comment]
@timscullin I believe you are correct. Do you mind opening up a new issue for this, that way our team can set aside time to look into it.

**Comment by timscullin** [comment]
Done

**Comment by jperegoy** [comment]
This feature appears to have regressed. On a fresh install @ `"react-imgix": "^9.5.0",` I am seeing the original behavior of `%20` being encoded to `%2520` again, though this time with the `disablePathEncoding` bool set to `true`.

Happy to set this up as a new issue, if that's preferable, but opted to keep things tidier here for now.

**Comment by sherwinski** [comment]
Thanks for the tip @jperegoy, someone from the team will investigate and report back here. And we can keep the conversation here for now.

**Comment by jperegoy** [comment]
Scratch this. Issue does not appear to be related to Imgix, but rather some ambitious encoding hidden away in ReactDomServer's rendering methods. Sorry for the false alarm, carry on.
