### ISSUE TITLE
Request for support for top-level alt prop

### ISSUE THREAD

**Issue by chrisirhc** [imgix/react-imgix#841]
**Is your feature request related to a problem? Please describe.**
alt text is generally recommended for SEO and accessibility of a website.
These are commonly looked side-by-side with image compression/optimization needs.

**Describe the solution you'd like**
I'd like the `alt` prop to be supported and the value of it passed to the underlying img tag.

**Describe alternatives you've considered**
I found that the alt attribute is supported through `htmlAttributes`. However, I'd think this prop comes up more often than not, and with similar regularity to `className`.
I've used `htmlAttributes` to unblock myself but I still find this rather surprising.

**Additional context**
I'm a little surprised that react-imgix doesn't support the alt prop out-of-the-box. It comes as a surprise as I was converting some img tags to Imgix components.

**Comment by luqven** [comment]
Hey @chrisirhc thanks for taking the time to open up this feature request.

I can see how having `alt` under `htmlAttributes` is a pain point.

If you're up for it, I definitely encourage you to open to a PR where `alt` is exposed as a top-level prop.

In the meantime, I’m going to add this feature request to our backlog until we can discuss it as a team. Once we have a timeline for implementing this, I’ll provide an update here.

**Comment by sherwinski** [comment]
Hey @chrisirhc, this prop should now be supported in [v9.4.0](https://github.com/imgix/react-imgix/releases/tag/v9.4.0). Let us know if you have any other questions, thanks!
