### ISSUE TITLE
Height and Weight are set to 0

### ISSUE THREAD

**Issue by ahmettahasakar** [imgix/react-imgix#856]
I tried to have a drop in replacement with my current <img> tags. It seemed to work directly. I am using nextjs. When changing pages of similar designs, the Imgix tags sometimes have weight="0" and height="0". Therefore no image is displayed. I noticed that this is happening, if the previous page had hardcoded height and width, and the next page doesn't have any dimensions specified. Is this a known behaviour? How can I fix it? If I access the page directly from the url, it works as expected.

**Comment by luqven** [comment]
Hey 👋🏼 @ahmettahasakar thanks for opening this issue.

Sounds like you're trying to replace your existing `<img>` tags with our `<Imgix>` component and for some reason, the images when rendered have their `width` and `height` attributes set to `0`.

Without being able to see the code I can't be certain as to why that might be. Do you think you could share an example repo or some example code? Also if you could also note the version of `react-imgix` you're running that'd be helpful as well.

**Comment by sherwinski** [comment]
Closing this as there hasn't been much activity or follow up. @ahmettahasakar please let us know this is still an issue or if you came across a workaround that you're willing to share.
