### ISSUE TITLE
React18 support

### ISSUE THREAD

**Issue by willemliufdmg** [imgix/react-imgix#866]
**Before you submit:**

- [:heavy_check_mark: ] Please search through the existing issues (both open AND closed) to see if your issue has been discussed before. GitHub issue search can be used for this: https://github.com/imgix/react-imgix/issues?utf8=%E2%9C%93&q=is%3Aissue
- [ :heavy_check_mark:] Please ensure the problem has been isolated and reduced. This link explains more: http://css-tricks.com/6263-reduced-test-cases/

**Describe the bug**
When using React@18 I get the following error while installing react-imgix:

```
...
npm ERR! Found: react@18.0.0
npm ERR! node_modules/react
npm ERR!   react@"^18.0.0" from the root project
npm ERR!
npm ERR! peer react@"15.x || 16.x || 17.x" from react-imgix@9.5.0
npm ERR! node_modules/react-imgix
npm ERR!   react-imgix@"^9.5.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
...
```

**To Reproduce**
Install latest React. Install react-imgix.

**Expected behaviour**
Should install react-imgix without any problems.

**Screenshots**
N/A

**Information:**

- react-imgix version: v9.5

**Comment by sherwinski** [comment]
Hey @willemliufdmg and thanks for opening this issue. We'll look into this within the next week and get back to you with any updates.

**Comment by alan-cooney** [comment]
Looks like this is being resolved in #862 - any update on that?

**Comment by sherwinski** [comment]
Hi @alan-cooney, our team is actively investigating this at the moment so I'll post any updates here as soon as I have them.

**Comment by sherwinski** [comment]
Hey everyone, the latest release ([v9.5.1](https://github.com/imgix/react-imgix/releases/tag/v9.5.1)) should now support react 18 🎉 
Closing this now but feel free to comment back if there are any further questions/issues.
