### ISSUE TITLE
image not showing in microsoft edge

### ISSUE THREAD

**Issue by RomanPersikov** [imgix/react-imgix#873]
Hello!
I get a picture from https://myproject.imgix.net/operator/5413/logo/ and it is displayed correctly in google chrome, but is not displayed in microsoft edge. Can you please tell me why this is happening and how to fix it?

**Comment by sherwinski** [comment]
Hey there @RomanPersikov 👋 

Can you provide the full image URL? This URL appears to be missing a file name.
If you'd prefer to not send it over a public channel like GH, please feel free to write in to our [support team](support@imgix.com) and they will be able to help you.

**Comment by luqven** [comment]
Hey @RomanPersikov,

Were you able to send us the full URL?

Again, if you'd prefer to not send it over a public channel like GH, please feel free to write in to our [support team](https://github.com/orgs/imgix/projects/4/views/support@imgix.com) and they will be able to help you.

**Comment by luqven** [comment]
Closing this issue unless/until more information can be provided. Please feel free to comment if you're still experiencing this issue and thank you again for reporting it.
