### ISSUE TITLE
Typesetting Endpoint ~text

### ISSUE THREAD

**Issue by MatayoshiMariano** [imgix/react-imgix#889]
Is [~text](https://docs.imgix.com/apis/rendering/typesetting/~text) supported in this library?

Thanks!

**Comment by luqven** [comment]
Hey @MatayoshiMariano, thanks for opening this issue.

Could you provide us with some example code of what you're trying to achieve? Not sure what you mean by `~text` "support". Are you trying to do some composting?

You _can_ use `~text` with this library. For example:

```jsx
<Imgix 
  src="https://my-domain.imgix.net/~text"
  imgixParams={{ 
    'fm':'png',
    'txt-size':36,
    'w':600,
    'txt-font':'Avenir+Next+Condensed,Bold',
    'txt':'The quick brown fox jumps over the lazy dog. The five boxing wizards jump quickly.',
    'txt-pad':30,
    'bg':'3D4C5F',
    'txt-color':'fff'
  }}
/>
```

The above would render `https://my-domain.imgix.net/~text?auto=format&fm=png&txt-size=36&txt-font=Avenir%2BNext%2BCondensed%2CBold&txt=The%20quick%20brown%20fox%20jumps%20over%20the%20lazy%20dog.%20The%20five%20boxing%20wizards%20jump%20quickly.&txt-pad=30&bg=3D4C5F&txt-color=fff&ixlib=react-9.5.4`

Which would render something like this:

![image](https://user-images.githubusercontent.com/16711614/207117429-7ea2c4d6-d838-4165-9eb3-873d84145aa1.png)

Hopefully that helps, but happy to answer any other questions.

**Comment by MatayoshiMariano** [comment]
@luqven thanks a lot! we're actually trying to do a blender so we can put a multiline text on top of an image
