### ISSUE TITLE
Width and height HTML attributes with fluid image

### ISSUE THREAD

**Issue by tremby** [imgix/react-imgix#891]
**Before you submit:**

- [x] Please read the [contributing guidelines](CONTRIBUTING.md)
- [x] Please search through the existing issues (both open AND closed) to see if your feature has already been discussed. Github issue search can be used for this: https://github.com/imgix/vue/issues?utf8=%E2%9C%93&q=is%3Aissue
- [x] Please take a moment to find out whether your idea fits with the scope and aims of the project

**Is your feature request related to a problem? Please describe.**

[It's best practice to specify width and height on images](https://web.dev/optimize-cls/), even if they are fluid, to help avoid layout shift. It tells the browser the expected size before it loads any image data, and an aspect ratio is derived from it so the browser can still know the image size even if CSS or something else is altering the image's width from its intrinsic one.

But I cannot find a way to allow width and height attributes to get through to the browser when using the react-imgix component while leaving the image fluid width. As soon as I specify width and height, react-imgix assumes I want a fixed-width image, and it gives resolution descriptors in the srcset instead of width descriptors (and then my sizes attribute is ignored by the browser, as per spec).

**Describe the solution you'd like**

There should be a way to let imgix know the width and height of the image so it can pass it through to the browser, without signalling that you want a fixed size image. Perhaps allowing them to be added to `htmlAttributes` would be simplest.

**Describe alternatives you've considered**

I've tried adding width and height properties to `htmlAttributes` but they don't make it to the browser.

The only other alternative I can think of is not to use this component.

**Comment by tremby** [comment]
Related, I saw some recent-ish patches removing width and height from `<source>` elements in `<picture>`. [Those are now allowed (and encouraged), however](https://chromestatus.com/feature/5737185317748736).

**Comment by luqven** [comment]
Hey @tremby, thanks for opening this issue.

I toyed with this for a bit, and I agree that we should be able to pass down `width, height` via the `htmlAttributes` prop when they're not set on the component's `width` and `height` props. 

You're suggestion, LGTM. If you are okay with opening a PR, that'd be great, and we'd be happy to give you quick and constructive feedback.

Otherwise, we'll tackle this sometime next year.

Thanks!

**Comment by tremby** [comment]
Another option would be a flag to explicitly tell the component if the user wants width descriptors or resolution descriptors. Which route seems best to you?

**Comment by luqven** [comment]
That's interesting! Can you tell me more about how you'd want that to look/work?

My instinct says your initial suggestion will be quicker to implement. Then, we can always follow up with a flag for width/resolution descriptors after some discussion.

Would that work for you?

**Comment by tremby** [comment]
I don't know about the rest of the web dev world but it's extremely rare that I want an actual [fixed size image, in terms of how many CSS pixels it measures](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images#resolution_switching_same_size_different_resolutions). In almost all cases I want a [fluid sized image](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images#resolution_switching_different_sizes).

So for my money, the width and height parameters wouldn't hint to Imgix what kind of srcset to produce at all, they'd just be passed wholesale through to the `img` element it produces, and the component would by default produce a srcset with width descriptors.

In the rare cases where I do want resolution descriptors (1x, 1.5x, etc), I do need some way to hint that to the component. I was considering a boolean flag, `fixedSize` or something, but it occurs to me that the `sizes` attribute would do the trick. It doesn't need to be parsed; its presence is enough -- [as per the spec, the `sizes` attribute is only used when the srcset uses width descriptors only](https://html.spec.whatwg.org/multipage/images.html#srcset-attributes).

So it makes sense to me to produce width descriptors in the srcset when `sizes` is present, or resolution descriptors if `sizes` is absent (or falsy). That would be my proposal. It'd be a breaking change, however. Now that I look, [it sounds from the docs like this is now Nextjs's next/image component does it too](https://nextjs.org/docs/api-reference/next/image#sizes).

Having said all that, I can do all of the above with the patch I originally proposed plus a wrapper component. So yeah, like you said, this may be something to suggest for a future release, whereas allowing width/height to be ignored by the component but passed through to the `img` element is simple enough and does the job for now, and shouldn't break anything.

**Comment by tremby** [comment]
See #892
