### ISSUE TITLE
Background component doesn't utilize ImgixProvider's domain parameter

### ISSUE THREAD

**Issue by mtzo09-dev** [imgix/react-imgix#931]
**Describe the bug**
In my Next.js application, I've wrapped my components using the `ImgixProvider` from the `react-imgix` library, specifying a domain for Imgix components. While all Imgix components correctly utilize this domain parameter, the `Background` component fails to do so.

**To Reproduce**

- Wrap a Background component with the ImgixProvider.
- Set the domain within the provider.
- Provide a source for the background without including the domain.
- Observe the error that occurs.

```js
import { Background, ImgixProvider } from 'react-imgix'

 <ImgixProvider domain={IMGIX_DOMAIN}>
      <Imgix
        src="image.jpg"
        width={100}
      /> {/* The Imgix component successfully uses the domain from the Provider */}
      <Background src="image.png" className="blog-title">
        <h2>Blog Title</h2>
      </Background> {/* The Background component fails to utilize the domain from the Provider */}
 </ImgixProvider>
```

**Expected behaviour**
I expect the Background component to correctly utilize the domain specified in the ImgixProvider, ensuring consistent behavior across all Imgix components.

**Comment by longevitytina** [comment]
Hi @mtzo09-dev. We are looking into this, thank you for the thorough issue description.

**Comment by longevitytina** [comment]
@mtzo09-dev we have released a rc tag if you want to try out the changes while we are testing. 
You can update you react-imgix in package.json to `9.8.1-rc.2` or see this [sandbox](https://codesandbox.io/p/sandbox/react-imgix-bg-9-8-1-rc-2-forked-8jjm4p?file=%2Fsrc%2Fstyle.css%3A19%2C17) with the rc tag applied

**Comment by mtzo09-dev** [comment]
Thank you, @longevitytina! I'll definitely test the changes with my team. Also, thank you for letting me know about the release candidate tag. We'll give it a try and provide feedback accordingly.
