### ISSUE TITLE
`disablePathEncoding` in `buildUrl` does not work

### ISSUE THREAD

**Issue by paulyi** [imgix/react-imgix#949]
**Before you submit:**

- [x] Please read the [contributing guidelines](CONTRIBUTING.md)
- [x] Please search through the existing issues (both open AND closed) to see if your issue has been discussed before. Github issue search can be used for this: https://github.com/imgix/vue/issues?utf8=%E2%9C%93&q=is%3Aissue
- [x] Please ensure the problem has been isolated and reduced. This link explains more: http://css-tricks.com/6263-reduced-test-cases/

**Describe the bug**
The third set of parameters to `buildUrl`, which include `disablePathEncoding`, are not being forwarded to the underlying `buildUrl` call and therefore not taking effect.

**To Reproduce**
Steps to reproduce the behaviour:
1. Call `buildUrl` with a URL containing spaces in the path
2. Pass in `{ disablePathEncoding: true }` as the third option to `buildUrl`
3. It returns an encoded URL

**Expected behaviour**
Result should not be encoded

**Screenshots**

**Information:**
react-imgix: `9.8.1`

**Additional context**
It seems like the third set of options passed into `buildUrlPublic` is never forwarded onto the `constructUrl` call.

https://github.com/imgix/react-imgix/blob/main/src/constructUrl.js#L160

**Comment by arno-fukuda** [comment]
Thank you for calling this out.

`{ disablePathEncoding: true }` should now work properly in  `v9.8.2`.
